;----------------------------------------------------------
;            COLORS
;----------------------------------------------------------

[colors]
rounds =            #1e222a
background =        ${xrdb:background}
text =              #161821
background-alt =    #444
foreground =        ${xrdb:foreground}
foreground-alt =    #555
primary =           ${xrdb:color5}
secondary =         #e60053
alert =             #bd2c40
magenta =           ${xrdb:color5}
green =             ${xrdb:color2}
blue =              ${xrdb:color4}
red =               ${xrdb:color1}
yellow =            ${xrdb:color3}
cyan =              ${xrdb:color6}

[bar/bar]
monitor = ${env:MONITOR:}
width = 100%
height = 30
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

wm-restack = i3

bottom = true

spacing = 2

scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev

border-size = 4
border-color = ${colors.background}

font-0 = TerminessTTF Nerd Font Mono:style=Bold:pixelsize=16;2
font-1 = JetBrainsMono Nerd Font:size=14;2

modules-left = launcher i3 bluetooth 
modules-center = date 
modules-right = wlan temp pulseaudio battery powermenu

cursor-click = pointer
cursor-scroll = 

line-size = 3

tray-position = left
tray-padding = 2
tray-background = ${colors.primary}

;----------------------------------------------------------
;            M O D U L E S
;----------------------------------------------------------

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false


; Only show workspaces on the same output as thebar
pin-workspaces = true

label-mode-padding = 1
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-underline = ${colors.primary}
label-focused-padding = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 1
label-unfocused-underline = 

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-padding = 1

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.red}
label-urgent-underline = ${colors.red}
label-urgent-padding = 1
; Separator in between workspaces
; label-separator = |

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = %{A1:alacritty -e bpytop &:} %{A}
format = %{A1:alacritty -e bpytop &:}<label>%{A}
format-prefix-foreground = ${colors.primary}
format-prefix-font = 3
format-padding = 2
;format-underline = #f90000
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 6
format-prefix = " "
format-prefix-foreground = ${colors.green}
format-prefix-font = 3
format-padding = 2
;format-underline = #4bffdc
label = %percentage_used%%

[module/temp]
type = internal/temperature
interval = 6.0
thermal-zone = 0
warn-temperature = 70

format = <label>
format-padding = 2
format-underline = 
format-warn = <label-warn>
format-warn-padding = 2
format-warn-foreground = ${colors.red}

label = %temperature-c%
label-warn =  %temperature-c%

[module/wlan]
type = internal/network
interface = ${env:DEFAULT_NETWORK_INTERFACE} 
interval = 1

format-connected-prefix = %{A1:~/.config/rofi/wifi.sh:} %{A}
format-connected-prefix-foreground = ${colors.primary}
format-connected-prefix-padding = 1
;format-connected-prefix-underline = ${colors.primary}
format-connected-prefix-font = 3
format-connected = %{A1:~/.config/rofi/wifi.sh:}<label-connected>%{A}
format-connected-padding = 1
label-connected =  %essid%󰧟%downspeed%

;format-prefix-connected-underline = ${colors.primary}

format-disconnected-prefix = " "
format-disconnected-prefix-foreground = ${colors.primary}
format-disconnected-prefix-padding = 1
;format-disconnected-prefix-underline = ${colors.primary}
format-disconnected-prefix-font = 3
format-disconnected = %{A1:~/.config/rofi/wifi.sh:}<label-disconnected>%{A}
format-disconnected-padding = 1
label-disconnected = " no connection"

[module/date]
type = internal/date
interval = 60
date = %a, %d %b
date-alt = 
time = %k:%M %p
time-alt = 
label = %date% %time%
format = %{A1:gnome-calendar&:}<label>%{A}
format-padding = 2
format-prefix = %{A1:gnome-calendar&:} %{A}
format-prefix-foreground = ${colors.primary}
format-prefix-font = 3
format-prefix-padding = 1

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
format-volume-padding = 
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume-prefix-font = 3
label-volume ="%percentage%%"

format-muted-prefix = " "
format-muted-prefix-font = 3
label-muted = muted

[module/battery]
type = internal/battery

full-at = 98

battery = BAT1
adapter = AC1

poll-interval = 1

time-format = %H:%M

format-charging = %{A1:~/bin/battery-info.sh &:}<animation-charging> <label-charging>%{A}
format-discharging = %{A1:~/bin/battery-info.sh &:}<ramp-capacity> <label-discharging>%{A}

format-full = %{A1:~/bin/battery-info.sh &:}<ramp-capacity><label-full>%{A}
format-full-foreground = #08f26e
label-full = %percentage%%
label-charging = %percentage%%
label-discharging = %percentage%% %time% %consumption%W
format-charging-padding = 2
format-discharging-padding = 2
format-full-padding = 2

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-1-foreground = ${colors.alert}
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

[module/powermenu]
type = custom/text
content = " "
content-foreground = ${colors.red}
content-font = 3
content-padding = 1
click-left = ~/.config/rofi/powermenu.sh

[module/bluetooth]
type = custom/script
exec = "bluetoothctl paired-devices | cut -d' ' -f2 | xargs -i -n1 bash -c "bluetoothctl info {} | grep -q 'Connected: yes' && bluetoothctl info {} | grep -o 'Alias: .*'" | awk -vORS=', ' '{sub($1 OFS,"")}1' | sed -e 's/, $//'"
exec-if = "[ $(bluetoothctl show | grep 'Powered: yes' | wc -l) -gt 0 ]"
interval = 5
click-left = ~/.config/rofi/bluetooth.sh
format-prefix = "  "
format-prefix-foreground = ${colors.blue}
format-prefix-font = 3
;format-prefix-underline = ${colors.blue}

[module/launcher]
type = custom/script
exec = "echo ' 﩯 '"
format-foreground = ${colors.blue}
click-left = ~/.config/rofi/apps.sh

[settings]
screenchange-reload = true

; vim:ft=dosini
;
; format = %{A1:"action goes here" &:}<label>%{A}
