[colors]
;background = #88040811
background = #00000000
background-1 = #416a88
background-2 = #638faa
background-3 = #2b4866
background-4 = #85aec8
background-5 = #a2b4bf
background-6 = #040811
background-7 = #04B486
urgent = #ff0000

;foreground = #ffffff
foreground = #000000
foreground-alt = #222222
primary = #EEEFFD
secondary = #EEEFFD


[bar/bar]
monitor = ${env:MONITOR:}
width = 1366
height = 25
offset-x = 0%
offset-y = 0%
radius = 2.0
fixed-center = true
top = true

background = ${colors.background}
foreground = ${colors.foreground}

;line-size = 0
line-color = #ff0000

underline-size = 2
line-size = 2

border-size = 5
border-color = #00ff0000

padding-left = 0
padding-right = 0

module-margin-left = 0
module-margin-right = 0
;module-margin-background = ${colors.background-1}

font-0 = Roboto:pixelsize=10;1
font-1 = FontAwesome:pixelsize=10;1
font-2 = sm4tik:pixelsize=10;1

modules-left = i3
modules-center = 
modules-right = xkeyboard volume wlan battery xbacklight date

[module/i3]
type = internal/i3
enable-click = true
enable-scroll = true
wrapping-scroll = true

ws-icon-0 = 1; terminal
ws-icon-1 = 2; chrome
ws-icon-2 = 3; spotify
ws-icon-3 = 4; social 

ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;
ws-icon-default = 

format = <label-state> <label-mode>

label-focused = %icon%
label-focused-background = ${colors.background-4}
;label-focused-underline = ${color-background-7}
;label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = 2

label-unfocused = %icon%
label-unfocused-padding = 2

label-occupied = %icon%
label-occupied-padding = 2

label-urgent = %icon%
label-urgent-background = ${colors.urgent}
label-urgent-padding = 2

label-empty = %icon%
label-empty-foreground = #44ffffff
label-empty-padding = 4


[module/spotify]
type = custom/script
interval = 10
format-background = ${colors.background-7}
format-padding = 2
exec = python /home/angelaguayo/spotify.py -t 42

[module/next]
type = custom/script
exec = echo 

format-padding = 1
format = <label>
;format-foreground = ${colors.my_foreground}
format-background = ${colors.background-7}
click-left = playerctl next

;[module/music]
;type = custom/script
;exec = if [[ "$(playerctl status)" = "Playing" ]]; then playerctl metadata xesam:artist; echo -n " - "; playerctl metadata xesam:title; else echo -n ""; fi
;exec-if = [[ "$(playerctl status)" = "Playing" || "$(playerctl status)" = "Paused" ]] && echo "0"
;interval = 1
;format = <label>

[module/wlan]
type = internal/network
interface = wlp2s0
interval = 3.0

format-connected =  <ramp-signal>
format-connected-padding = 2
;format-connected-background = ${colors.background-1}

format-disconnected-padding = 1
format-disconnected-background = #ff0000

ramp-signal-0 = 0
ramp-signal-1 = 1
ramp-signal-2 = 2
ramp-signal-3 = 3
ramp-signal-4 = 4
ramp-signal-5 = 5
ramp-signal-6 = 6
ramp-signal-7 = 7


[module/battery]
type = internal/battery
battery = BAT0
adapter = ACAD
full-at = 87

label-charging =  %percentage%%
;label-charging-foreground = ${colors.background-alt}
format-charging =  <animation-charging> <label-charging>
;format-charging-background = ${colors.background-1}
format-charging-padding = 1

label-discharging = %percentage%%  
format-discharging =  <ramp-capacity> <label-discharging>
;format-discharging-background = ${colors.background-1}
format-discharging-padding = 1

label-full = %percentage%%
;format-full-background = ${colors.background-1}
;format-full-foreground = ${colors.background-1}
format-full-padding = 2
format-padding = 2

ramp-capacity-0 =  
ramp-capacity-1 =  
ramp-capacity-2 =  
ramp-capacity-3 =  
ramp-capacity-4 =  

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
;animation-charging-foreground = ${colors.background-alt}
animation-charging-framerate = 750


[module/xbacklight]
type = internal/xbacklight

format =  <label> <bar>
label = "  "
;label-background = ${colors.background-1}
bar-width = 10
bar-indicator = │
bar-indicator-foreground = #ff
;bar-indicator-background = ${colors.background-1}
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
;bar-fill-background = ${colors.background-1}
bar-empty = ─
bar-empty-font = 2
;bar-empty-background = ${colors.background-1}
;format-full-background = ${colors.background-1}

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight


[module/date]
type = internal/date
interval = 1

time = "%H:%M"
time-alt = "%Y-%m-%d, %H:%M"

format-prefix-foreground = ${colors.foreground-alt}
format-padding = 2
;format-background = ${colors.background-3}
format-background-underline = ${colors.background-3}
format = %{A1:gsimplecal & disown:}  <label> %{A}
label = %date% %time%

[module/volume]
type = internal/volume

;format-muted-background = ${colors.background-1}
;format-volume-background = ${colors.background-1}
format-volume-padding = 2
format-volume = "<ramp-volume> <label-volume>"
label-muted = " mute"

; Only applies if <ramp-volume> is used
ramp-volume-0 =  
ramp-volume-1 = 
ramp-volume-2 = 

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout =  %layout%
label-layout-padding = 2
;label-layout-background = ${colors.background-1}

label-indicator-padding = 2
;label-indicator-background = ${colors.background-1}

[module/weather]
type = custom/script
interval = 10
;format-background = ${colors.background-2}
format-padding = 2
format = <label>
format-prefix = " "
exec = python3 ~/.config/polybar/weather

[settings]
screenchange-reload = true

[global/wm]
margin-top = 30
margin-bottom = 5
wm-restack = i3
