set-option -ga terminal-overrides ",xterm-256color:Tc"

# These make tmux transparent again
set -g "window-style" "bg=default"
set -g "window-active-style" "bg=default"

set mouse on

# action key
unbind C-b
set-option -g prefix C-a
set-option -g repeat-time 0

# Reload settings
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux display-popup -E ~/.dotfiles/bin/bin/tmux-sessionizer"

# ThePrimeagen cht.sh script
bind-key -r i run-shell "tmux neww ~/.dotfiles/bin/bin/tmux-cht.sh"

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# Split panes with \ and -
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# status line
set-option -g status-position bottom

set-option status-style fg=default,bg=default

set -g status on
set -g status-interval 2
set -g status-left-length 60
set -g status-left '#[fg=colour235,bg=colour252,bold] #S #[fg=colour252,bg=colour238,nobold]#[fg=colour245,bg=colour238,bold] #(whoami) #[fg=colour238,bg=colour234,nobold]'

set -g status-right-length 150
set -g status-right '#[fg=colour59]#[fg=colour255,bg=colour59] #[fg=colour254,bold]#[fg=colour16,bg=colour254,bold] #h '

set -g window-status-separator '#[fg=colour244,bg=colour234] '
set -g window-status-format "#[fg=colour244,bg=colour234] #I #[fg=colour240] #[default,bg=colour234]#W "
set -g window-status-current-format "#[fg=colour234,bg=colour31]#[fg=colour117,bg=colour31] #I  #[fg=colour231,bold]#W #[fg=colour31,bg=colour234,nobold]"
