set -g terminal-overrides 'xterm*:smcup@:rmcup@'
# These make tmux transparent again
set -g "window-style" "bg=default"
set -g "window-active-style" "bg=default"

set-window-option -g mode-keys vi
set mouse on

# action key
unbind C-b
set-option -g prefix C-a
set-option -g repeat-time 0


#open current dir
bind o run-shell "thunar #{pane_current_path}"

# Reload settings
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# launch calcurse
bind-key -r P run-shell "tmux neww python3 -c 'help()'"

# browse through all available manpages
bind-key -r b run-shell "tmux neww ~/.dotfiles/bin/bin/tmux-manpages"

# theme switcher using fzf and pywal
bind-key -r t run-shell "tmux neww ~/.dotfiles/bin/bin/tmux-themeswitcher"

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/.dotfiles/bin/bin/tmux-sessionizer"

# ThePrimeagen cht.sh script
bind-key -r i run-shell "tmux neww ~/.dotfiles/bin/bin/tmux-cht.sh"

# ThePrimeagen cht.sh script
bind-key -r T run-shell "tmux neww ~/.dotfiles/bin/bin/tmux-trans"

# create/kill session
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# Split panes with \ and -
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# status line
set-option -g status-position bottom

set-option status-style fg=default,bg=default

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'jimeh/tmux-themepack'

set -g @themepack 'powerline/default/green'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
