return {
  "ibhagwan/fzf-lua",
  config = function()
    local actions = require "fzf-lua.actions"
    require 'fzf-lua'.setup {
      winopts       = {
        border     = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
        backdrop   = 60,
        fullscreen = false,
        height     = 1,
        width      = 1,
        row        = 1,
        col        = 0,
        preview    = {
          border       = 'noborder',
          wrap         = 'nowrap',
          hidden       = 'nohidden',
          vertical     = 'down:60%',
          horizontal   = 'right:40%',
          layout       = 'vertical',
          flip_columns = 100,
          title        = true,
          title_pos    = "center",
          scrollbar    = 'float',
          scrolloff    = '-2',
          scrollchars  = { '█', '' },
          delay        = 100,
          winopts      = {
            number         = true,
            relativenumber = false,
            cursorline     = true,
            cursorlineopt  = 'both',
            cursorcolumn   = false,
            signcolumn     = 'no',
            list           = false,
            foldenable     = false,
            foldmethod     = 'manual',
          },
        },
        on_create  = function()
          -- called once upon creation of the fzf main window
          -- can be used to add custom fzf-lua mappings, e.g:
          --   vim.keymap.set("t", "<C-j>", "<Down>", { silent = true, buffer = true })
        end,
      },
      keymap        = {
        builtin = {
          false,
          ["<M-Esc>"]    = "hide",
          ["<F1>"]       = "toggle-help",
          ["<F2>"]       = "toggle-fullscreen",
          ["<F3>"]       = "toggle-preview-wrap",
          ["<F4>"]       = "toggle-preview",
          ["<F5>"]       = "toggle-preview-ccw",
          ["<F6>"]       = "toggle-preview-cw",
          ["<F7>"]       = "toggle-preview-ts-ctx",
          ["<S-Left>"]   = "preview-reset",
          ["<S-down>"]   = "preview-page-down",
          ["<S-up>"]     = "preview-page-up",
          ["<M-S-down>"] = "preview-down",
          ["<M-S-up>"]   = "preview-up",
        },
        fzf = {
          false,
          ["ctrl-z"]     = "abort",
          ["ctrl-u"]     = "unix-line-discard",
          ["ctrl-f"]     = "half-page-down",
          ["ctrl-b"]     = "half-page-up",
          ["ctrl-a"]     = "beginning-of-line",
          ["ctrl-e"]     = "end-of-line",
          ["alt-a"]      = "toggle-all",
          ["alt-g"]      = "first",
          ["alt-G"]      = "last",
          ["f3"]         = "toggle-preview-wrap",
          ["f4"]         = "toggle-preview",
          ["shift-down"] = "preview-page-down",
          ["shift-up"]   = "preview-page-up",
          ["ctrl-l"]     = "select-all+accept",
        },
      },
      actions       = {
        files = {
          false,
          ["enter"]  = actions.file_edit_or_qf,
          ["ctrl-s"] = actions.file_split,
          ["ctrl-v"] = actions.file_vsplit,
          ["ctrl-t"] = actions.file_tabedit,
          ["alt-q"]  = actions.file_sel_to_qf,
          ["alt-Q"]  = actions.file_sel_to_ll,
        },
      }    }
  end,
  keys = {
    { "<leader>F",       ":FzfLua<CR>",                                                       desc = "Pickers" },
    { "<leader><space>", ":FzfLua buffers<CR>",                                               desc = "Buffers" },
    { "<leader>ff",      ":FzfLua files<CR>",                                                 desc = "Find Files" },
    { "<leader>fr",      ":FzfLua resume<CR>",                                                desc = "Resume" },
    { "<leader>fc",      function() require('fzf-lua').files({ cwd = '~/.config/nvim' }) end, desc = "Config files" },
    { "<leader>fg",      ":FzfLua live_grep<CR>",                                             desc = "Grep (Root Dir)" },
    { "<leader>gs",      ":FzfLua git_status<CR>",                                            desc = "Status" },
    { "<leader>gc",      ":FzfLua git_commits<CR>",                                           desc = "Commits" },
    { "<leader>gC",      ":FzfLua git_bcommits<CR>",                                          desc = "Current file back commits" },
    { "<leader>fw",      ":FzfLua grep_cword<CR>",                                            desc = "Grep word under cursor" },
    { "<leader>fW",      ":FzfLua grep_cWORD<CR>",                                            desc = "Grep WORD under cursor" },
    { "<leader>fw",      ":FzfLua grep_visual<CR>",                                           desc = "Grep visual selection",    mode = "v" },
    { "<leader>fF",      ":FzfLua filetypes<CR>",                                             desc = "Change filetype" },
  }
}
